export default [
  {
    id: 1,
    question: 'What is the speed of light?',
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 2,
    question: "Define Newton's first law of motion.",
    subject: 'Physics',
    topic: 'Mechanics',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 3,
    question: 'Explain the concept of inertia.',
    subject: 'Physics',
    topic: 'Mechanics',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 4,
    question: 'What is the formula for calculating kinetic energy?',
    subject: 'Physics',
    topic: 'Energy',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 5,
    question: "Define the term 'refraction' in the context of optics.",
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 6,
    question: "State Ohm's Law and provide its formula.",
    subject: 'Physics',
    topic: 'Electricity',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 7,
    question: 'What is the function of a catalyst in a chemical reaction?',
    subject: 'Chemistry',
    topic: 'Chemical Reactions',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 8,
    question: 'Explain the concept of osmosis.',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 9,
    question: "Define the term 'photosynthesis' and its significance.",
    subject: 'Biology',
    topic: 'Photosynthesis',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 10,
    question: 'What is the primary function of the nervous system?',
    subject: 'Biology',
    topic: 'Nervous System',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 11,
    question: 'Explain the concept of gravitational force.',
    subject: 'Physics',
    topic: 'Gravity',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 12,
    question: 'List the three states of matter and describe their characteristics.',
    subject: 'Chemistry',
    topic: 'States of Matter',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 13,
    question: 'What is the difference between a prokaryotic and eukaryotic cell?',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 14,
    question: 'Explain the concept of work in physics.',
    subject: 'Physics',
    topic: 'Work and Energy',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 15,
    question: "Define the term 'acid' in chemistry.",
    subject: 'Chemistry',
    topic: 'Acids and Bases',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 16,
    question: 'What is the structure of an atom?',
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 17,
    question: 'Explain the process of mitosis in cell division.',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 18,
    question: 'What are the basic principles of natural selection?',
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 19,
    question: 'Define the concept of electric current.',
    subject: 'Physics',
    topic: 'Electricity',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 20,
    question: 'Explain the laws of conservation of energy.',
    subject: 'Physics',
    topic: 'Energy',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 21,
    question: 'What is the difference between covalent and ionic bonds?',
    subject: 'Chemistry',
    topic: 'Chemical Bonds',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 22,
    question: 'Describe the structure and function of DNA.',
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 23,
    question: 'What is the role of enzymes in biological processes?',
    subject: 'Biology',
    topic: 'Biochemistry',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 24,
    question: 'Define the concept of acceleration in physics.',
    subject: 'Physics',
    topic: 'Motion',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 25,
    question: 'Explain the principles of chemical equilibrium.',
    subject: 'Chemistry',
    topic: 'Chemical Equilibrium',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 26,
    question: 'What is the role of chloroplasts in plant cells?',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 27,
    question: 'Discuss the laws of reflection in optics.',
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 28,
    question: 'Define the concept of pH in chemistry.',
    subject: 'Chemistry',
    topic: 'Acids and Bases',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 29,
    question: 'Explain the process of nuclear fission.',
    subject: 'Physics',
    topic: 'Nuclear Physics',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 30,
    question: 'What is the structure of the periodic table?',
    subject: 'Chemistry',
    topic: 'Periodic Table',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 31,
    question: 'Describe the process of natural gas formation.',
    subject: 'Chemistry',
    topic: 'Chemical Reactions',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 32,
    question: 'Solve for x: 2x + 5 = 15',
    subject: 'Mathematics',
    topic: 'Algebra',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 33,
    question: 'Calculate the area of a circle with radius 6 cm.',
    subject: 'Mathematics',
    topic: 'Geometry',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 34,
    question: 'Explain the process of natural selection in evolution.',
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 35,
    question: 'Factorize the quadratic expression: x^2 + 5x + 6',
    subject: 'Mathematics',
    topic: 'Algebra',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 36,
    question: 'Simplify the expression: (3x + 2)(2x - 5)',
    subject: 'Mathematics',
    topic: 'Algebra',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 37,
    question: 'What is the chemical symbol for gold?',
    subject: 'Chemistry',
    topic: 'Elements',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 38,
    question: 'Balance the chemical equation: H2 + O2 → H2O',
    subject: 'Chemistry',
    topic: 'Chemical Reactions',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 39,
    question: 'Explain the process of meiosis in cell division.',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 40,
    question: 'What is the SI unit of electric charge?',
    subject: 'Physics',
    topic: 'Electricity',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 41,
    question: "Define the term 'molecule' in chemistry.",
    subject: 'Chemistry',
    topic: 'Chemical Bonds',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 42,
    question: 'Explain the greenhouse effect in environmental science.',
    subject: 'Environmental Science',
    topic: 'Climate Change',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 43,
    question: 'What is the Pythagorean theorem?',
    subject: 'Mathematics',
    topic: 'Geometry',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 44,
    question: 'Name the stages of cellular respiration.',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 45,
    question: 'Define the concept of voltage in electricity.',
    subject: 'Physics',
    topic: 'Electricity',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    id: 46,
    question: 'What is the molecular formula for water?',
    subject: 'Chemistry',
    topic: 'Chemical Formulas',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 47,
    question: 'Explain the process of transcription in genetics.',
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 48,
    question: 'What is the law of conservation of mass in chemistry?',
    subject: 'Chemistry',
    topic: 'Chemical Reactions',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    id: 49,
    question: 'Differentiate between velocity and acceleration in physics.',
    subject: 'Physics',
    topic: 'Motion',
    difficulty: 'Hard',
    marks: 15,
  },
  {
    id: 50,
    question: 'What is the formula for the area of a triangle?',
    subject: 'Mathematics',
    topic: 'Geometry',
    difficulty: 'Easy',
    marks: 5,
  },
]
